sudo: required
language: python
  - "3.6"


services:
  - docker


install:
  - docker volume create --name=db-volume
  - docker volume ls


script:
  - docker-compose up -d
  - docker-compose ps

  - docker-compose run --rm api python manage.py makemigrations todo_api
  - docker-compose run --rm api python manage.py migrate
  - docker-compose run --rm api python manage.py test

  - docker-compose down

notifications:
  email: false
