sudo: required
language: python
  - "3.6"


services:
  - docker


script:
  - docker-compose up -d
  - docker-compose ps

  - docker-compose run --rm api python manage.py makemigrations todo_api
  - docker-compose run --rm api python manage.py migrate
  - docker-compose run --rm api python manage.py test todo_api

  - docker-compose down

notifications:
  email: false
