version: "3"

services:
  # APPLICATION
  api:
    image: fantaso/django-rest-api:1
    container_name: django-rest-api
    build:
      context: ./django_rest
      dockerfile: Dockerfile
    labels:
      /todo: "Django restframework to interact with the todo api"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_rest:/django-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # DATABASE
  db:
    image: postgres:11.2
    container_name: django-rest-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=todo-postgres
      - POSTGRES_PASSWORD=todo-password
      - PGDATA=/django-db
    volumes:
      - db-volume:/django-db
      
  # DATABASE CLIENT
  db_client:
    image: adminer
    container_name: django-rest-db-client
    ports:
      - "8080:8080"

volumes:
  db-volume:
    external: true
